IMPORT AACT;
fName := AACT.FileName_Prefix + 'responsible_parties_txt';
Responsible_Parties := RECORD
  STRING RESPONSIBLE_PARTY_ID;
  STRING NCT_ID;
  STRING NAME_TITLE;
  STRING ORGANIZATION;
  STRING RESPONSIBLE_PARTY_TYPE;
  STRING INVESTIGATOR_AFFILIATION;
  STRING INVESTIGATOR_FULL_NAME;
  STRING INVESTIGATOR_TITLE;
END;
ds := DATASET(fName, Responsible_Parties, CSV(HEADING(1),SEPARATOR('|'),TERMINATOR('\r\n')));

EXPORT File_Responsible_Parties := ds;